[general]
shuffle_caption = false
caption_extension = '.txt'
keep_tokens = 1

[[datasets]]
resolution = 512
batch_size = 1
keep_tokens = 1

  [[datasets.subsets]]
  image_dir = '/home/phigep/pinokio/api/fluxgym.git/datasets/personal-lora-fluxdev-keyword'
  class_tokens = '<phigep>'
  num_repeats = 10